"""Verified updates for the Windows one-file release, downloaded only after consent."""
from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import urllib.request


RELEASE_API = (
    "https://api.github.com/repos/phamphuongquynh0307/"
    "Auto_PGsharp_byQpham/releases/latest"
)
EXE_NAME = "AutoCatchPokemonPGSharp.exe"
HASH_NAME = "AutoCatchPokemonPGSharp.exe.sha256"


def newer(candidate: str, current: str) -> bool:
    def parts(value: str) -> tuple[int, ...] | None:
        match = re.fullmatch(r"v?(\d+)\.(\d+)\.(\d+)", value)
        return tuple(map(int, match.groups())) if match else None

    target, installed = parts(candidate), parts(current)
    return target is not None and installed is not None and target > installed


def _get(url: str, *, limit: int) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "AutoCatchPokemonPGSharp-Updater"})
    with urllib.request.urlopen(request, timeout=20) as response:
        data = response.read(limit + 1)
    if len(data) > limit:
        raise ValueError("Update response exceeds size limit")
    return data


def available_update(current: str) -> dict | None:
    """Check release metadata without downloading the EXE or its checksum."""
    release = json.loads(_get(RELEASE_API, limit=1_000_000))
    return release if newer(release.get("tag_name", ""), current) else None


def download_update(release: dict, exe_path: str) -> tuple[str, Path]:
    """Return (version, verified staged EXE) for a release the user accepted.

    The digest is a release asset generated by our build job. Old releases without it
    cannot be installed automatically. All three URLs must be GitHub HTTPS URLs.
    """
    version = release.get("tag_name", "")
    if not re.fullmatch(r"v\d+\.\d+\.\d+", version):
        raise ValueError("Invalid release version")
    assets = {asset.get("name"): asset.get("browser_download_url")
              for asset in release.get("assets", [])}
    def asset_url(name: str) -> str:
        url = assets.get(name)
        prefix = ("https://github.com/phamphuongquynh0307/"
                  "Auto_PGsharp_byQpham/releases/download/")
        if not isinstance(url, str) or not url.startswith(prefix):
            raise ValueError(f"Missing trusted release asset: {name}")
        return url

    digest = _get(asset_url(HASH_NAME), limit=256).decode("ascii").strip().split()[0]
    if not re.fullmatch(r"[0-9a-fA-F]{64}", digest):
        raise ValueError("Invalid update digest")
    target = Path(exe_path)
    staged = target.with_name(target.name + ".update")
    source = asset_url(EXE_NAME)
    request = urllib.request.Request(source, headers={"User-Agent": "AutoCatchPokemonPGSharp-Updater"})
    hasher = hashlib.sha256()
    try:
        with urllib.request.urlopen(request, timeout=60) as response, staged.open("wb") as output:
            total = 0
            while block := response.read(1024 * 1024):
                total += len(block)
                if total > 400_000_000:
                    raise ValueError("Update exceeds size limit")
                hasher.update(block)
                output.write(block)
        if hasher.hexdigest().lower() != digest.lower():
            raise ValueError("Update digest mismatch")
    except Exception:
        staged.unlink(missing_ok=True)
        raise
    return version, staged


def install_on_exit(exe_path: str, staged: Path) -> None:
    """Start a detached helper that waits for this process, swaps the EXE, then restarts."""
    if not getattr(sys, "frozen", False) or os.name != "nt":
        return
    helper = Path(tempfile.gettempdir()) / f"avc-update-{os.getpid()}.ps1"
    # Paths are passed as process arguments rather than interpolated into PowerShell code.
    helper.write_text(
        "param([int]$ParentPid, [string]$Exe, [string]$Staged)\n"
        "try { Wait-Process -Id $ParentPid -ErrorAction SilentlyContinue } catch {}\n"
        "for ($i = 0; $i -lt 30; $i++) {\n"
        "  try { Move-Item -LiteralPath $Staged -Destination $Exe -Force -ErrorAction Stop; "
        "Start-Process -FilePath $Exe -WorkingDirectory (Split-Path -Parent $Exe); break }\n"
        "  catch { Start-Sleep -Seconds 1 }\n"
        "}\n"
        "Remove-Item -LiteralPath $PSCommandPath -Force -ErrorAction SilentlyContinue\n",
        encoding="utf-8",
    )
    subprocess.Popen(
        ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File",
         str(helper), "-ParentPid", str(os.getpid()), "-Exe", exe_path,
         "-Staged", str(staged)],
        creationflags=subprocess.CREATE_NO_WINDOW | subprocess.DETACHED_PROCESS,
        close_fds=True,
    )
