"""Verified updates for the Windows one-file release, downloaded only after consent."""
from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import urllib.request


RELEASE_API = (
    "https://api.github.com/repos/phamphuongquynh0307/"
    "Auto_PGsharp_byQpham/releases/latest"
)
EXE_NAME = "AutoCatchPokemonPGSharp.exe"
HASH_NAME = "AutoCatchPokemonPGSharp.exe.sha256"


def newer(candidate: str, current: str) -> bool:
    def parts(value: str) -> tuple[int, ...] | None:
        match = re.fullmatch(r"v?(\d+)\.(\d+)\.(\d+)", value)
        return tuple(map(int, match.groups())) if match else None

    target, installed = parts(candidate), parts(current)
    return target is not None and installed is not None and target > installed


def _get(url: str, *, limit: int) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "AutoCatchPokemonPGSharp-Updater"})
    with urllib.request.urlopen(request, timeout=20) as response:
        data = response.read(limit + 1)
    if len(data) > limit:
        raise ValueError("Update response exceeds size limit")
    return data


def available_update(current: str) -> dict | None:
    """Check release metadata without downloading the EXE or its checksum."""
    release = json.loads(_get(RELEASE_API, limit=1_000_000))
    return release if newer(release.get("tag_name", ""), current) else None


def download_update(release: dict, exe_path: str) -> tuple[str, Path]:
    """Return (version, verified staged EXE) for a release the user accepted.

    The digest is a release asset generated by our build job. Old releases without it
    cannot be installed automatically. All three URLs must be GitHub HTTPS URLs.
    """
    version = release.get("tag_name", "")
    if not re.fullmatch(r"v\d+\.\d+\.\d+", version):
        raise ValueError("Invalid release version")
    assets = {asset.get("name"): asset.get("browser_download_url")
              for asset in release.get("assets", [])}
    def asset_url(name: str) -> str:
        url = assets.get(name)
        prefix = ("https://github.com/phamphuongquynh0307/"
                  "Auto_PGsharp_byQpham/releases/download/")
        if not isinstance(url, str) or not url.startswith(prefix):
            raise ValueError(f"Missing trusted release asset: {name}")
        return url

    digest = _get(asset_url(HASH_NAME), limit=256).decode("ascii").strip().split()[0]
    if not re.fullmatch(r"[0-9a-fA-F]{64}", digest):
        raise ValueError("Invalid update digest")
    staged = _staged_path(exe_path)
    # Written under .part and renamed only once verified, so a download cut short by closing
    # the app can never be mistaken for a finished one.
    partial = staged.with_name(staged.name + ".part")
    staged.unlink(missing_ok=True)
    source = asset_url(EXE_NAME)
    request = urllib.request.Request(source, headers={"User-Agent": "AutoCatchPokemonPGSharp-Updater"})
    hasher = hashlib.sha256()
    try:
        with urllib.request.urlopen(request, timeout=60) as response, partial.open("wb") as output:
            total = 0
            while block := response.read(1024 * 1024):
                total += len(block)
                if total > 400_000_000:
                    raise ValueError("Update exceeds size limit")
                hasher.update(block)
                output.write(block)
        if hasher.hexdigest().lower() != digest.lower():
            raise ValueError("Update digest mismatch")
        os.replace(partial, staged)
    except Exception:
        partial.unlink(missing_ok=True)
        raise
    return version, staged


def _staged_path(exe_path: str) -> Path:
    target = Path(exe_path)
    return target.with_name(target.name + ".update")


def discard_stale(exe_path: str) -> None:
    """Remove leftovers of an update that was never installed (e.g. the app was killed)."""
    staged = _staged_path(exe_path)
    for leftover in (staged, staged.with_name(staged.name + ".part")):
        try:
            leftover.unlink(missing_ok=True)
        except OSError:
            pass


def _clean_environment() -> dict[str, str]:
    """This process's environment, minus what makes a one-file EXE think it is our child.

    The PyInstaller bootloader passes _PYI_* variables to its own child process. Inherited by
    the updated EXE, they make it reuse this run's _MEI folder — which is deleted as we exit —
    so the new version never opens. PYINSTALLER_RESET_ENVIRONMENT makes it start fresh.
    """
    env = {key: value for key, value in os.environ.items()
           if not key.upper().startswith(("_PYI_", "_MEIPASS"))}
    env["PYINSTALLER_RESET_ENVIRONMENT"] = "1"
    return env


def install_on_exit(exe_path: str, staged: Path) -> None:
    """Start a detached helper that waits for this app, swaps the EXE, then restarts it."""
    if not getattr(sys, "frozen", False) or os.name != "nt":
        return
    helper = Path(tempfile.gettempdir()) / f"avc-update-{os.getpid()}.ps1"
    # Paths are passed as process arguments rather than interpolated into PowerShell code.
    # Both processes of the one-file build are waited for: the bootloader parent keeps the
    # EXE locked until it has cleaned up _MEI. If the swap still cannot happen, the old EXE
    # is reopened anyway rather than leaving the user with no app at all.
    helper.write_text(
        "param([string]$Pids, [string]$Exe, [string]$Staged)\n"
        "foreach ($p in ($Pids -split ',')) { try { Wait-Process -Id $p -Timeout 60 -ErrorAction Stop } catch {} }\n"
        "$moved = $false\n"
        "for ($i = 0; $i -lt 120 -and -not $moved; $i++) {\n"
        "  try { Move-Item -LiteralPath $Staged -Destination $Exe -Force -ErrorAction Stop; $moved = $true }\n"
        "  catch { Start-Sleep -Seconds 1 }\n"
        "}\n"
        "Start-Process -FilePath $Exe -WorkingDirectory (Split-Path -Parent $Exe)\n"
        "Remove-Item -LiteralPath $PSCommandPath -Force -ErrorAction SilentlyContinue\n",
        encoding="utf-8",
    )
    pids = ",".join(str(pid) for pid in {os.getpid(), os.getppid()})
    args = ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File",
            str(helper), "-Pids", pids, "-Exe", exe_path, "-Staged", str(staged)]
    flags = subprocess.CREATE_NO_WINDOW | subprocess.DETACHED_PROCESS
    # Leave any job object we were started in, or closing the app can take the helper with
    # it. A job that forbids breakaway refuses the flag outright, so fall back without it.
    try:
        subprocess.Popen(args, env=_clean_environment(), close_fds=True,
                         creationflags=flags | subprocess.CREATE_BREAKAWAY_FROM_JOB)
    except OSError:
        subprocess.Popen(args, env=_clean_environment(), close_fds=True, creationflags=flags)
